server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:2m}

spring:
  application:
    name: ${SPRING_APP_NAME:springsecsecurity1}
  config:
    import: "optional:classpath:application_prod.yml"
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:%green(%d{HH:mm:ss:SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15})- %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:Trace}
    com:
      eazybytes:
        springsecsecurity1: info