server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:10m}

spring:
  application:
    name: ${SPRING_APP_NAME:springsecsecurity1}
  config:
    activate:
      on-profile: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQLDialect

#  security:
#    user:
#      name: ${SECURITY_USERNAME:eazybytes}
#      password: ${SECURITY_PASSWORD:12345}

logging:
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:%green(%d{HH:mm:ss:SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15})- %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}